config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :market_places
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market_place.rb
# frozen_string_literal: true

class MarketPlace < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/market_places_controller.rb
# frozen_string_literal: true

class MarketPlacesController < ApplicationController
  before_action :set_market_place, only: %i[show edit update destroy]

  # GET /market_places
  # GET /market_places.json
  def index
    @market_places = case params[:line]
                     when 'Products'
                       MarketPlace.where('line LIKE ?', "%#{params[:line]}%")
                     # A was pressed
                     when 'Services'
                       # B was pressed
                       MarketPlace.where('line LIKE ?', "%#{params[:line]}%")
                     when 'Food'
                       # C was pressed
                       MarketPlace.where('line LIKE ?', "%#{params[:line]}%")
                     else
                       MarketPlace.all
                     end

    # @market_places = MarketPlace.where("line LIKE ?", "%#{params[:line]}%")
    # @market_places = MarketPlace.all
  end

  # GET /market_places/1
  # GET /market_places/1.json
  def show; end

  # GET /market_places/new
  def new
    @market_place = MarketPlace.new
  end

  # GET /market_places/1/edit
  def edit; end

  # POST /market_places
  # POST /market_places.json
  def create
    @market_place = MarketPlace.new(market_place_params)

    respond_to do |format|
      if @market_place.save
        format.html { redirect_to @market_place, notice: 'Market place was successfully created.' }
        format.json { render :show, status: :created, location: @market_place }
      else
        format.html { render :new }
        format.json { render json: @market_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /market_places/1
  # PATCH/PUT /market_places/1.json
  def update
    respond_to do |format|
      if @market_place.update(market_place_params)
        format.html { redirect_to @market_place, notice: 'Market place was successfully updated.' }
        format.json { render :show, status: :ok, location: @market_place }
      else
        format.html { render :edit }
        format.json { render json: @market_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /market_places/1
  # DELETE /market_places/1.json
  def destroy
    @market_place.destroy
    respond_to do |format|
      format.html { redirect_to market_places_url, notice: 'Market place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_market_place
    @market_place = MarketPlace.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def market_place_params
    params.require(:market_place).permit(:name, :address, :district, :postcode, :line, :pickup_type, :open_hour,
                                         :close_hour, :service_days)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/market_places_helper.rb
# frozen_string_literal: true

module MarketPlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/market_places/_form.html.erb
<%= form_with(model: market_place, local: true) do |form| %>
  <% if market_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(market_place.errors.count, "error") %> prohibited this market_place from being saved:</h2>

      <ul>
        <% market_place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode %>
  </div>

  <div class="field">
    <%= form.label :line %>
    <%= form.text_area :line %>
  </div>

  <div class="field">
    <%= form.label :pickup_type %>
    <%= form.check_box :pickup_type %>
  </div>

  <div class="field">
    <%= form.label :open_hour %>
    <%= form.time_select :open_hour %>
  </div>

  <div class="field">
    <%= form.label :close_hour %>
    <%= form.time_select :close_hour %>
  </div>

  <div class="field">
    <%= form.label :service_days %>
    <%= form.text_field :service_days %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/market_places/edit.html.erb
<h1>Editing Market Place</h1>

<%= render 'form', market_place: @market_place %>

<%= link_to 'Show', @market_place %> |
<%= link_to 'Back', market_places_path %>

app/views/market_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Market Places</h1>

<!--
<%= form_tag market_places_path, method: :get do %>
  <div class="form-group">
    <%= text_field_tag :line, params[:line], class: "form-control", placeholder: "" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-primary btn-md" %>
<% end %>
-->

<%= form_tag market_places_path, method: :get do %>
 
  <%= submit_tag 'Products', name: 'line' %>
  <%= submit_tag 'Services', name: 'line' %>
  <%= submit_tag 'Food', name: 'line' %>
  <%= submit_tag 'All', name: 'line' %>

<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>District</th>
      <th>Postcode</th>
      <th>Line</th>
      <th>Pickup type</th>
      <th>Open hour</th>
      <th>Close hour</th>
      <th>Service days</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @market_places.each do |market_place| %>
      <tr>
        <td><%= market_place.name %></td>
        <td><%= market_place.address %></td>
        <td><%= market_place.district %></td>
        <td><%= market_place.postcode %></td>
        <td><%= market_place.line %></td>
        <td><%= market_place.pickup_type %></td>
        <td><%= market_place.open_hour %></td>
        <td><%= market_place.close_hour %></td>
        <td><%= market_place.service_days %></td>
        <td><%= link_to 'Show', market_place %></td>
        <td><%= link_to 'Edit', edit_market_place_path(market_place) %></td>
        <td><%= link_to 'Destroy', market_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Market Place', new_market_place_path %>

app/views/market_places/new.html.erb
<h1>New Market Place</h1>

<%= render 'form', market_place: @market_place %>

<%= link_to 'Back', market_places_path %>

app/views/market_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @market_place.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @market_place.address %>
</p>

<p>
  <strong>District:</strong>
  <%= @market_place.district %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @market_place.postcode %>
</p>

<p>
  <strong>Line:</strong>
  <%= @market_place.line %>
</p>

<p>
  <strong>Pickup type:</strong>
  <%= @market_place.pickup_type %>
</p>

<p>
  <strong>Open hour:</strong>
  <%= @market_place.open_hour %>
</p>

<p>
  <strong>Close hour:</strong>
  <%= @market_place.close_hour %>
</p>

<p>
  <strong>Service days:</strong>
  <%= @market_place.service_days %>
</p>

<%= link_to 'Edit', edit_market_place_path(@market_place) %> |
<%= link_to 'Back', market_places_path %>